
[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
numReplicas = 1
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[service]
port = "80"
staticPublishPath = "./dist"
